Fix deleteDatabase blocking due to open connections
JuulLabs/indexeddb pull request #144
Opened 2024-01-23 09:40 UTC by janne-koschinski

Automatically close database connections on delete
Handle "blocked" event in deleteDatabase

2024-01-26 08:51 UTC, janne-koschinski commented
If there's anything we'll need to change to allow this to merge, please feel free to contact me, currently this is blocking us quite a bit :/

2024-01-31 00:01 UTC, cedrickcooke requested changes
Sorry for the delay, last week was quite busy and I had to do some research to understand exactly what was happening. The IDB event names were not intuitive to me 😅.

We don't have a public facing style guide (~~yet? I'll look into it~~ apparently I was wrong, relevant portion [here](https://github.com/JuulLabs/kotlin-guides?tab=readme-ov-file#checknotnull)), but could you please replace the `!!` with `checkNotNull`? Our convention is to use `!!` when the value is guaranteed non-null but the compiler can't figure it out, and `checkNotNull` when things _shouldn't_ be null but might be due to logic errors. I'll approve after that, thanks for handling this

2024-01-31 17:01 UTC, cedrickcooke approved these changes

2024-01-31 17:01 UTC, cedrickcooke commented on core/src/jsMain/kotlin/Database.kt
> +    internal fun ensureDatabase(): IDBDatabase = checkNotNull(database) { "database is closed" }
Great idea, love that it gives us a description

2024-01-31 17:14 UTC, davidtaylor-juul approved these changes

2024-01-31 17:23 UTC, merged